In [2]:
import numpy as np


## some important array functions
# np.array() # any python sequences to the numpy array object

np.array([10,20,304,2023,100],dtype=np.int64)
#np.arange() # create an array with regularly incrementing the values
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
# creating the 2D matrix using np.eye,np.diag and np.vander

# creating an identity matrix

print(np.eye(3,5)) # rows and columns index elements are 1 else 0

print("np.diag = ")
print(np.diag([1,2,4]))# putting the elements in diagonal and rests are zero

# vanderMonde matrix: it is 2D matrix where each columns of this matrix is decreasing power of the input 1D arrayt or list or tuple x, where the highest polynomial order is n-1
print("np.vander = ")
print(np.vander([1,2,3,4,5,6],3))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
np.diag = 
[[1 0 0]
 [0 2 0]
 [0 0 4]]
np.vander = 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]]


In [17]:
# general ndarray creation function
# the functions are np.ones,np.zeros and random

print(np.ones((2,3),dtype=np.float64)) # create 2D array with ones all place

print("creating a 2D array with random values.....")
print(np.random.randn(10).reshape(2,5).astype(float))

[[1. 1. 1.]
 [1. 1. 1.]]
creating a 2D array with random values.....
[[ 0.75925282 -0.90957794 -1.09132772  0.0329365  -0.79942606]
 [ 0.96157466  2.77051237 -1.47503964  0.18657141  1.06301892]]


In [ ]:
# numpy.indices will create a set of arrays(stacked as one higher dimensioned array),one per dimensions with repsreseting variation in that dimensions
print(np.indices((3,3)))

In [ ]:
# replicating and joining or mutating the existing array
from copy import deepcopy
#light on shallow copy and deep copy
ll = [10,20,30,50,102] 
# creates a shallow copy or we can say that it provides a view and assign a reffrence to the old list. so changes reflects on both
ll2 = ll[3:] # it creates the new list and copy the new elements to the list
print(ll2)
ll2[0] = 1091
print("Does it change int ll = " , ll)
print("Does it change int ll = " , ll2)
print("After slicing ll = ",ll)

# to create a deep copy u can use copy.deepcopy() method
ll2 = deepcopy(ll)
ll[0] = 100
print("After deeep copy = ")
print(ll2)

[50, 102]
Does it change int ll =  [1999, 20, 30, 50, 102]
Does it change int ll =  [1091, 102]
After slicing ll =  [1999, 20, 30, 50, 102]
After deeep copy = 
[1999, 20, 30, 50, 102]


# Shallow Copy vs Deep Copy in Python

## Shallow Copy
- Creates a new object but references the original object's elements
- Changes to nested objects affect both copies
- Created using: `copy()` method, `list()`, `dict()`, or slice operations `[:]`
- In NumPy: `view()` method, simple assignment with slicing

## Deep Copy
- Creates a completely independent clone with all nested objects copied
- Changes to nested objects only affect that specific copy
- Created using: `copy.deepcopy()` method from the `copy` module
- In NumPy: `copy()` method